# Generated by Django 4.0 on 2024-06-25 19:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('competences_recherchees', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDÉ', 'Validé'), ('REFUSÉ', 'Refusé')], default='EN_ATTENTE', max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_contrat', models.CharField(max_length=200)),
                ('nom_entreprise_employeur', models.CharField(max_length=20)),
                ('contact_entreprise', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_entreprise', models.EmailField(max_length=200)),
                ('adresse_entreprise', models.CharField(max_length=50)),
                ('nom_employe', models.CharField(max_length=20)),
                ('prenom_employe', models.CharField(max_length=150)),
                ('contact_employe', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_employe', models.EmailField(max_length=200)),
                ('adresse_employe', models.CharField(max_length=50)),
                ('type_remuneration', models.CharField(choices=[('MO', 'Par mois'), ('JO', 'Par jour'), ('HE', 'Par heure')], max_length=2)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.employe')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause', models.TextField(blank=True, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr.contrat')),
            ],
        ),
    ]
